
Admin on 2016-May-07, Saturday
CREATE TABLE [2445LO37EUREGP] (Id COUNTER CONSTRAINT PrimaryKey PRIMARY KEY, ProjNm TEXT (40), CntrctrNm TEXT (40), CntrctNm TEXT (40), Cur_EUR DOUBLE , Cur_EGP DOUBLE );
