
Admin on 2016-May-08, Sunday
CREATE TABLE [1647LO39EURGBP] (Id COUNTER CONSTRAINT PrimaryKey PRIMARY KEY, ProjNm TEXT (40), CntrctrNm TEXT (40), CntrctNm TEXT (40), Cur_EUR DOUBLE , Cur_GBP DOUBLE );
