
Admin on 2016-May-08, Sunday
CREATE TABLE [2245DA37AEDCHF] (Id COUNTER CONSTRAINT PrimaryKey PRIMARY KEY, ProjNm TEXT (40), CntrctrNm TEXT (40), CntrctNm TEXT (40), Cur_AED DOUBLE , Cur_CHF DOUBLE );
